apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 87bc08e538e366dfa170912017273d85f7ad79bf
    app.quarkus.io/build-timestamp: 2023-02-28 - 11:18:06 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: code-with-quarkus
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP