apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
spec:
  description: Infrstructure services
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: "*"
    - name: dev-cluster
      server: "https://35.185.139.117"
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - git@github.com:paolocarta/gitops-repo-cicd-presentation.git