apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces-management
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infra
  source:
    repoURL: git@github.com:paolocarta/gitops-repo-cicd-presentation.git
    targetRevision: master
    path: infra/management-cluster/namespaces
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m