apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports/maven
            name: gce-maven-nfs-disk
          - mountPath: /exports/workspace
            name: gce-jenkins-workspace-nfs-disk
      volumes:
        - name: gce-maven-nfs-disk
          gcePersistentDisk:
            pdName: gce-maven-nfs-disk
            fsType: ext4
        - name: gce-jenkins-workspace-nfs-disk
          gcePersistentDisk:
            pdName: gce-jenkins-workspace-nfs-disk
            fsType: ext4