apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-with-quarkus
spec:
  replicas: 2
  template:
    spec:
      containers:
        - image: gcr.io/paolos-playground-323415/code-with-quarkus:11-gitops
          name: code-with-quarkus