apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: TBD

resources:
  - ../../base/code-with-quarkus

patchesStrategicMerge:
  - deployment.yaml

  

# nameSuffix: -tbd

# replicas:
#   - name: code-with-quarkus
#     count: 1

